### ISSUE TITLE
Accept "current" as value for set_desktop_for_window

### ISSUE THREAD

**Issue by Zayon** [jinliu/kdotool#12]
It would be great to be able to do this:

`kdotool search --name 'XXX' set_desktop_for_window current windowactivate`

That would be the equivalent of `kdotool search --name 'XXX' set_desktop_for_window $(kdotool get_desktop) windowactivate`.

The goal is to be able to do something like this:

`kdotool --shortcut Meta+something --name "pull XXX window" --name 'XXX' set_desktop_for_window current windowactivate` because it does not work with the `$()` notation

**Comment by jinliu** [comment]
Please use "current_desktop".
