### ISSUE TITLE
Call kdotool rapidly will make journalctl generating huge amount of garbage data.

### ISSUE THREAD

**Issue by Neutron3529** [jinliu/kdotool#13]
Since KWin decided to use journalctl to record script output, if we want to record mouse locaion rapidly (e.g., using /dev/uinput to simulate a absolute mouse move), the log file blows up to hundered MBs.

I wonder if there is some alternative approaches that is feasable. For example, running a backend with root permissions that could obtain kwin's mouse location with `libc::process_vm_readv`.

I performed some attempt, and got [this](https://github.com/Neutron3529/kwin-mouse-loc)

Feel free to copy the code into your project:)

**Comment by jinliu** [comment]
I'll change it to only generate log when `--debug` is specified. Hopefully that helps.
