### ISSUE TITLE
kdotool getwindowid [WINDOW] returns the kwin id instead of X11 window id

### ISSUE THREAD

**Issue by arkadesOrg** [jinliu/kdotool#16]
This makes no sense, as the kwin window id is already know at this point.
For bridging purposes it should return the X11 window id for further usage
with xprop for example.

**Comment by jinliu** [comment]
See https://github.com/jinliu/kdotool/pull/8 for the rationale of this command.

OTOH, it seems that the X11 window ID is not available to the kwin scripting API.

**Comment by arkadesOrg** [comment]
I see! Do you know any reliable way to set the window role of an application started from command line without the usage of PID? It seems as PID isnt reliable either because of intermediate processes for example.
