### ISSUE TITLE
search for name and square brackets

### ISSUE THREAD

**Issue by nobanzai** [jinliu/kdotool#4]
When searching for a window name containing square brackets I have to use 2 backslashes to quote the brackets with kdotool:

--name '(\\\\[Xconsolen\\\\])'

With xdotool one backslash is sufficient

--name '(\\[Xconsolen\\])'

Is this supposed to be correct?

**Comment by jinliu** [comment]
No, it's supposed to be the same as xdotool. I guess I forgot to escape the string when using it in regexp. Thanks for reporting!
