### ISSUE TITLE
Not working when called from a global shortcut

### ISSUE THREAD

**Issue by TamtamHero** [jinliu/kdotool#5]
setup: latest KDE Neon with plasma 6

kdotool works fine when run from terminal, but doesn't when caled from a script assigned to a global shortcut.

For instance, from terminal:
```
kdotool search ""
{fc91d79b-4a4a-419c-96f7-fcb4667470d3}
{21712d9c-829e-4bfc-8d4b-5ab3c98404fd}
```

But when the same command is called from within a bash script assigned to a shortcut (Settings/Shortcuts/Add New/Command or Script...) the output of `kdotool search "" ` inside the script is simply empty (same with --debug option).

Do you have any idea what is going wrong there ?

**Comment by jinliu** [comment]
Works for me.

`$ cat ~/bin/kdotool-test
#!/usr/bin/bash
notify-send "kdotool" "$(kdotool search)"
$ chmod +x ~/bin/kdotool-test
`

Then I bind Meta+Alt+M to "~/bin/kdotool-test", and it creates a notification of window ids.

Could you try if this works in your setup?

**Comment by jinliu** [comment]
Might be related to a parser bug that I fixed, but not released yet. Could you try the attachment?
[kdotool.tar.gz](https://github.com/jinliu/kdotool/files/14472788/kdotool.tar.gz)

**Comment by TamtamHero** [comment]
I simply had installed kdotool in a location not in the PATH for the shortcut deamon. That's it. Sorry for bothering, thanks for your time, work, and reactivity !
