### ISSUE TITLE
Can you add a command to show cursor coordinates in kde like in xdotool?

### ISSUE THREAD

**Issue by bakustarver** [jinliu/kdotool#7]
$ xdotool getwindowfocus getwindowname - shows x and y coordinates of the cursor on the display in x11

please add the similar command for kdotool as 
$ kdotool getactivewindow getwindowname

ydotool requires root to run and there is no such function there

Here a code for the command:
workspace_mxy                          = () => "x=" + workspace.cursorPos.x + "\ny=" + workspace.cursorPos.y;

**Comment by jinliu** [comment]
I think you mean `getmouselocation`?

Yes it's possible. I ignored all keyboard/mouse commands, because commands like `mousemove` are currently impossible without root. But `getmouselocation` can be done.

**Comment by bakustarver** [comment]
yes, sorry , getmouselocation
